apiVersion: v1
kind: Service
metadata:
  name: bankmanagementsystem-service
  namespace: bankmanagementsystem-ns
spec:
  type: NodePort
  selector:
    app: bankmanagementsystem
  ports:
  - port: 8100
    targetPort: 8100
    nodePort: 30081